"""
opto.features.recursive_opt
===========================
Robust + simple recursive (meta) optimization on Trace / Trace-Bench.

Two trainable surfaces (see levels.py for the full explanation):
  * SELECTION/CONFIG : LevelConfig + MetaLevel        (pick & configure components)
  * CODE/IMPLEMENTATION : ComponentSpec + CodeArtifactLevel  (rewrite component code)

Everything is a ``trace.Module``, so ``opto.trainer.train`` + any
``opto.optimizers`` optimizer drive every recursion level (O0..O3) unchanged.
"""

from .levels import (
    CapabilityArtifact,
    TimedGuide,
    invalid_result,
    LevelConfig,
    ArtifactLevel,
    MetaLevel,
    FamilyPolicyLevel,
    PriorInductionLevel,
    ComponentSpec,
    CodeArtifactLevel,
    RecursiveGuide,
    best_config_from,
    encode_cfg,
    decode_cfg,
    canonicalize_cfg_text,
    register_config_values,
    validate_config_field,
    validate_level_config,
)
from .memory import MemoryLite, EpisodeTrace, FamilyPrior, ArtifactRecord
from .capabilities import (
    AgenticOptimizer,
    default_optimizer_tools,
    parse_optimizer_tool_policy,
    select_optimizer_tools,
    TinkerEnvAdapter,
    HITLGate,
    auto_allow,
    run_search_policy, make_search_policy_tool, make_search_policy_evaluator,
)
from .decisions import (
    ConfidenceGate,
    GuardedDecision,
    GuardedDecisionCase,
    GuardedDecisionEvaluator,
    GuardedDecisionScore,
    guarded_feedback,
    keyword_present,
    make_guarded_decision_evaluator,
    parse_guarded_decision,
    score_guarded_decision,
)
from .budget import (
    BudgetExceeded,
    RecursiveOptBudget,
    budget_status,
    configure_budget_from_env,
    current_budget,
    reset_budget,
    make_budget,
    budget_to_spec_dict,
)
from . import traces, tracebench
from .effects import Effect, FieldEffect, EffectReport, InactiveFieldError, check_field_effects, effects_for
from .spec import (
    make_level_spec,
    agentic_optimizer_factory,
    score_spread,
    run_spec,
    compile_level,
    validate_spec,
    reuse_priors,
    save_priors,
    make_scored_task_runner,
)
from .optimize import (
    optimize,
    resolve_trainer,
    current_trainer,
    current_optimizer,
    current_iterations,
    current_num_candidates,
    TRAINER,
    OPTIMIZER,
    ITERATIONS,
    NUM_CANDIDATES,
)

__all__ = [
    "route_optimizers",
    "field_search_space",
    "is_numeric_field",
    "LeastSquaresOptimizer",
    "OptunaOptimizer",
    "seed_everything",
    "RepeatedResult",
    "run_spec_repeated",
    "resolve_numeric_search_space",
    "optimize_config_numeric",
    "budget_to_spec_dict",
    "make_budget",
    "CapabilityArtifact",
    "TimedGuide",
    "invalid_result",
    "LevelConfig",
    "ArtifactLevel",
    "MetaLevel",
    "FamilyPolicyLevel",
    "PriorInductionLevel",
    "ComponentSpec",
    "CodeArtifactLevel",
    "RecursiveGuide",
    "best_config_from",
    "encode_cfg",
    "decode_cfg",
    "canonicalize_cfg_text",
    "register_config_values",
    "validate_config_field",
    "validate_level_config",
    "MemoryLite",
    "EpisodeTrace",
    "FamilyPrior",
    "ArtifactRecord",
    "AgenticOptimizer",
    "default_optimizer_tools",
    "parse_optimizer_tool_policy",
    "select_optimizer_tools",
    "run_search_policy",
    "make_search_policy_tool",
    "make_search_policy_evaluator",
    "TinkerEnvAdapter",
    "HITLGate",
    "auto_allow",
    "ConfidenceGate",
    "GuardedDecision",
    "GuardedDecisionCase",
    "GuardedDecisionEvaluator",
    "GuardedDecisionScore",
    "guarded_feedback",
    "keyword_present",
    "make_guarded_decision_evaluator",
    "parse_guarded_decision",
    "score_guarded_decision",
    "BudgetExceeded",
    "RecursiveOptBudget",
    "budget_status",
    "configure_budget_from_env",
    "current_budget",
    "reset_budget",
    "traces",
    "tracebench",
    "optimize",
    "resolve_trainer",
    "current_trainer",
    "current_optimizer",
    "current_iterations",
    "current_num_candidates",
    "TRAINER",
    "OPTIMIZER",
    "ITERATIONS",
    "NUM_CANDIDATES",
    "run_spec",
    "agentic_optimizer_factory",
    "score_spread",
    "compile_level",
    "validate_spec",
    "reuse_priors",
    "save_priors",
    "make_scored_task_runner",
    "make_level_spec",
    "Effect",
    "FieldEffect",
    "EffectReport",
    "InactiveFieldError",
    "check_field_effects",
    "effects_for",
]

from .experiments import (
    run_spec_repeated,
    RepeatedResult,
    seed_everything,
    resolve_numeric_search_space,
    optimize_config_numeric,
)

from .numeric_optimizers import (OptunaOptimizer, LeastSquaresOptimizer, route_optimizers, field_search_space, is_numeric_field)
