from typing import List, Dict, Any, Union, Tuple, Optional, Callable
import contextvars
import json
import pickle
import re
import copy
import os
from opto.utils.llm import LLM, AbstractModel
from opto.trainer.suggest import Suggest


def exact_match_metric(question, student_answer, info):
    """ Exact match metric """
    return float(student_answer == info)

class Guide:
    """
    Base class for all guides that provide feedback on content.

    Guide evaluates generated content and provide feedback to help improve it.
    Different implementations may use different strategies for evaluation,
    such as LLM-based comparison, keyword matching, or custom verification.
    """

    def __call__(self, task: str, response: str, info: Any, **kwargs) -> Tuple[float, str]:
        """
        Generate feedback for the provided response.

        Args:
            task: The task to analyze (e.g., user query, task, etc.)
            response: The response generated by LLM (e.g., student answer, generated code)
            info: additional information (used by some suggest but not others)
            **kwargs: Optional reference information (e.g., expected answer, execution logs),
                     Additional context or parameters for specialized guide implementations

        Returns:
            score: score from the teacher
            feedback: feedback from the teacher
        """
        return self.forward(task, response, info, **kwargs)

    def forward(self, task: str, response: str, info: Any, **kwargs) -> Tuple[float, str]:
        return self.get_feedback(task, response, info, **kwargs)

    def get_feedback(self, query: str, response: str, reference: Optional[str] = None, **kwargs) -> Tuple[float, str]:
        raise NotImplementedError

    def metric(self, query: str, response: str, reference: Optional[str] = None, **kwargs) -> float:
        """ Exact match metric """
        return self.get_feedback(query, response, reference)[0]

    def get_score_dict(self, query: str, response: str, reference: Optional[str] = None, **kwargs) -> Dict[str, float]:
        """Return the evaluation score as a dictionary.

        Default implementation wraps the scalar from get_feedback() as
        {"score": float_value}. Subclasses returning multi-metric scores
        should override this method to return e.g.
        {"accuracy": 0.9, "fluency": 0.8, "latency_s": 0.05}.

        If get_feedback() returns a dict as its first element, that dict
        is returned directly (with values cast to float).
        """
        score = self.get_feedback(query, response, reference, **kwargs)[0]
        if isinstance(score, dict):
            return {k: float(v) for k, v in score.items()}
        return {"score": float(score)}

    def copy(self):
        """ Create a copy of the guide instance.

        Returns:
            A new instance of the same guide class with the same parameters.
        """
        # This is used in batch_run to create a new instance of the guide.
        # This can be overridden by subclasses to provide a more specific copy behavior.
        return copy.deepcopy(self)

    def save(self, path: str):
        """ Save the guide state to a file. """
        # check if the directory exists
        directory = os.path.dirname(path)
        if directory != "":
            os.makedirs(directory, exist_ok=True)
        with open(path, 'wb') as f:
            pickle.dump(self.__getstate__(), f)

    def load(self, path: str):
        """ Load the guide state from a file. """
        with open(path, 'rb') as f:
            state = pickle.load(f)
            self.__setstate__(state)

    # NOTE: overload __getstate__ and __setstate__ in subclasses to customize pickling behavior
    def __getstate__(self):
        state = self.__dict__.copy()
        return state

    def __setstate__(self, state):
        self.__dict__.update(state)


class UsageTrackingLLM:
    """Wrap an LLM and record token usage for the current execution context.

    The wrapper reads OpenAI-compatible usage metadata when available:
    ``response.usage.prompt_tokens`` and ``response.usage.completion_tokens``.
    Dict-shaped responses and ``input_tokens`` / ``output_tokens`` aliases are
    also supported.

    If usage metadata is missing, the wrapper estimates token counts with a
    simple whitespace split by default. Set ``estimate_missing=False`` to fail
    fast instead. Streaming usage is only captured when the provider returns
    usage on the response object passed back from the wrapped LLM.

    The usage store is ``ContextVar``-backed, so concurrent evaluations do not
    overwrite each other. ``__deepcopy__`` returns ``self`` intentionally:
    trainer code may deep-copy agent and guide independently, and both copies
    must keep sharing the same tracker instance.
    """

    def __init__(self, base_llm: Any, *, estimate_missing: bool = True) -> None:
        if not callable(base_llm):
            raise TypeError("base_llm must be callable")
        self._base = base_llm
        self.estimate_missing = estimate_missing
        self._usage: contextvars.ContextVar[Optional[Dict[str, int]]] = (
            contextvars.ContextVar("llm_token_usage", default=None)
        )
        self._usage_estimated: contextvars.ContextVar[bool] = contextvars.ContextVar(
            "llm_token_usage_estimated", default=False
        )

    def __deepcopy__(self, memo: Dict[int, Any]) -> "UsageTrackingLLM":
        memo[id(self)] = self
        return self

    def __getattr__(self, name: str) -> Any:
        try:
            base = self.__dict__["_base"]
        except KeyError as exc:
            raise AttributeError(name) from exc
        return getattr(base, name)

    def __call__(self, *args: Any, **kwargs: Any) -> Any:
        messages = kwargs.get("messages", args[0] if args else None)
        response = self._base(*args, **kwargs)
        tokens_in, tokens_out, estimated = self._read_token_usage(
            response=response,
            messages=messages,
        )
        self._add_usage(tokens_in=tokens_in, tokens_out=tokens_out)
        self._usage_estimated.set(self._usage_estimated.get() or estimated)
        return response

    def reset_usage(self) -> None:
        """Clear token usage for the current execution context."""
        self._usage.set(None)
        self._usage_estimated.set(False)

    def has_usage(self) -> bool:
        """Return whether any usage was recorded in this execution context."""
        return self._usage.get() is not None

    def last_usage(self, *, reset: bool = False) -> Dict[str, int]:
        """Return accumulated token usage for the current execution context.

        Args:
            reset: Clear the current context after reading when True.
        """
        usage = self._usage.get()
        result = (
            {"tokens_in": 0, "tokens_out": 0}
            if usage is None
            else {
                "tokens_in": int(usage.get("tokens_in", 0)),
                "tokens_out": int(usage.get("tokens_out", 0)),
            }
        )
        if reset:
            self.reset_usage()
        return result

    def last_usage_was_estimated(self) -> bool:
        """Return whether any current usage metric used fallback estimation."""
        return bool(self._usage_estimated.get())

    def __getstate__(self) -> Dict[str, Any]:
        state = self.__dict__.copy()
        state["_usage"] = None
        state["_usage_estimated"] = None
        return state

    def __setstate__(self, state: Dict[str, Any]) -> None:
        self.__dict__.update(state)
        self._usage = contextvars.ContextVar("llm_token_usage", default=None)
        self._usage_estimated = contextvars.ContextVar(
            "llm_token_usage_estimated", default=False
        )

    def _add_usage(self, *, tokens_in: int, tokens_out: int) -> None:
        previous = self._usage.get() or {"tokens_in": 0, "tokens_out": 0}
        self._usage.set(
            {
                "tokens_in": int(previous.get("tokens_in", 0)) + tokens_in,
                "tokens_out": int(previous.get("tokens_out", 0)) + tokens_out,
            }
        )

    def _read_token_usage(
        self,
        *,
        response: Any,
        messages: Any,
    ) -> Tuple[int, int, bool]:
        prompt_tokens, completion_tokens = self._extract_usage(response)
        estimated = False

        if prompt_tokens is None or completion_tokens is None:
            if not self.estimate_missing:
                raise ValueError(
                    "LLM response did not include complete token usage. "
                    "Use UsageTrackingLLM(..., estimate_missing=True) to "
                    "allow estimates, or use a provider/model that returns "
                    "response.usage."
                )
            estimated = True
            if prompt_tokens is None:
                prompt_tokens = self._estimate_prompt_tokens(messages)
            if completion_tokens is None:
                completion_tokens = self._estimate_completion_tokens(response)

        return int(prompt_tokens or 0), int(completion_tokens or 0), estimated

    @classmethod
    def _extract_usage(cls, response: Any) -> Tuple[Optional[int], Optional[int]]:
        usage = cls._get_field(response, "usage")
        prompt_tokens = cls._to_optional_int(
            cls._get_field(usage, "prompt_tokens", "input_tokens")
        )
        completion_tokens = cls._to_optional_int(
            cls._get_field(usage, "completion_tokens", "output_tokens")
        )
        return prompt_tokens, completion_tokens

    @staticmethod
    def _get_field(obj: Any, *names: str) -> Any:
        if obj is None:
            return None
        for name in names:
            value = None
            if isinstance(obj, dict) and name in obj:
                value = obj[name]
            elif hasattr(obj, name):
                value = getattr(obj, name)
            if value is not None:
                return value
        return None

    @staticmethod
    def _to_optional_int(value: Any) -> Optional[int]:
        if value is None:
            return None
        try:
            return int(value)
        except (TypeError, ValueError):
            return None

    @classmethod
    def _estimate_prompt_tokens(cls, messages: Any) -> int:
        if not isinstance(messages, list):
            return 0
        return len(
            " ".join(cls._message_to_text(message) for message in messages).split()
        )

    @classmethod
    def _message_to_text(cls, message: Any) -> str:
        if isinstance(message, dict):
            return cls._content_to_text(message.get("content", ""))
        return str(message)

    @classmethod
    def _content_to_text(cls, content: Any) -> str:
        if content is None:
            return ""
        if isinstance(content, str):
            return content
        if isinstance(content, list):
            return " ".join(cls._content_to_text(part) for part in content)
        if isinstance(content, dict):
            parts = []
            for key in ("text", "content"):
                if key in content:
                    parts.append(cls._content_to_text(content[key]))
            return " ".join(parts)
        return str(content)

    @classmethod
    def _estimate_completion_tokens(cls, response: Any) -> int:
        text = cls._completion_text(response)
        return len(text.split()) if text else 0

    @classmethod
    def _completion_text(cls, response: Any) -> str:
        if isinstance(response, str):
            return response

        choices = cls._get_field(response, "choices")
        if not choices:
            return ""

        choice = choices[0]
        message = cls._get_field(choice, "message")
        content = cls._get_field(message, "content")
        if content is None:
            content = cls._get_field(choice, "text")
        return "" if content is None else str(content)


class TokenUsageAugmentingGuide(Guide):
    """Add token usage metrics from a tracker to another guide's scores.

    The tracker must expose ``last_usage()``. ``UsageTrackingLLM`` is the default
    implementation, but custom LLM wrappers can be used if they follow the same
    duck-typed interface.
    """

    def __init__(
        self,
        base_guide: Guide,
        token_llm: Any,
        *,
        tokens_in_key: str = "tokens_in",
        tokens_out_key: str = "tokens_out",
        require_usage: bool = True,
        reset_after_read: bool = True,
    ) -> None:
        if not isinstance(base_guide, Guide):
            raise TypeError("base_guide must be a Guide")
        if not callable(getattr(token_llm, "last_usage", None)):
            raise TypeError("token_llm must expose a callable last_usage() method")
        if not tokens_in_key or not tokens_out_key:
            raise ValueError("token metric keys must be non-empty strings")
        self._base = base_guide
        self._token_llm = token_llm
        self.tokens_in_key = tokens_in_key
        self.tokens_out_key = tokens_out_key
        self.require_usage = require_usage
        self.reset_after_read = reset_after_read

    def __deepcopy__(self, memo: Dict[int, Any]) -> "TokenUsageAugmentingGuide":
        cls = type(self)
        new = cls.__new__(cls)
        memo[id(self)] = new
        new._base = copy.deepcopy(self._base, memo)
        new._token_llm = self._token_llm
        new.tokens_in_key = self.tokens_in_key
        new.tokens_out_key = self.tokens_out_key
        new.require_usage = self.require_usage
        new.reset_after_read = self.reset_after_read
        return new

    def get_feedback(
        self,
        query: str,
        response: str,
        reference: Optional[str] = None,
        **kwargs: Any,
    ) -> Tuple[float, str]:
        reward, feedback = self._base.get_feedback(
            query,
            response,
            reference=reference,
            **kwargs,
        )
        usage = self._usage_metrics()
        return (
            float(reward),
            (
                f"{feedback} "
                f"{self.tokens_in_key}={usage[self.tokens_in_key]:.0f} "
                f"{self.tokens_out_key}={usage[self.tokens_out_key]:.0f}"
            ),
        )

    def get_score_dict(
        self,
        query: str,
        response: str,
        reference: Optional[str] = None,
        **kwargs: Any,
    ) -> Dict[str, float]:
        score_dict = dict(
            self._base.get_score_dict(
                query,
                response,
                reference=reference,
                **kwargs,
            )
        )
        usage = self._usage_metrics()
        collisions = sorted(set(score_dict).intersection(usage))
        if collisions:
            raise ValueError(
                "Base guide already emitted token metric keys: "
                f"{collisions}. Use custom tokens_in_key/tokens_out_key."
            )
        score_dict.update(usage)
        return score_dict

    def _usage_metrics(self) -> Dict[str, float]:
        has_usage = getattr(self._token_llm, "has_usage", None)
        if self.require_usage and callable(has_usage) and not has_usage():
            raise RuntimeError(
                "No token usage was recorded before reading guide metrics. "
                "Ensure the evaluated agent uses the same UsageTrackingLLM "
                "instance passed to TokenUsageAugmentingGuide."
            )

        try:
            usage = self._token_llm.last_usage(reset=self.reset_after_read)
        except TypeError:
            usage = self._token_llm.last_usage()
            reset_usage = getattr(self._token_llm, "reset_usage", None)
            if self.reset_after_read and callable(reset_usage):
                reset_usage()

        return {
            self.tokens_in_key: float(
                usage.get("tokens_in", usage.get(self.tokens_in_key, 0))
            ),
            self.tokens_out_key: float(
                usage.get("tokens_out", usage.get(self.tokens_out_key, 0))
            ),
        }


class LLMJudge(Guide):
    """
    This is a combined metric + feedback guide that asks LLM to provide a binary judgment (True/False)
    and then if False, provide feedback.

    This is an implementation of LLM-as-a-judge.
    """

    DEFAULT_CORRECTNESS_TEMPLATE = "Correct [TERMINATE]"
    DEFAULT_INCORRECTNESS_TEMPLATE = "Incorrect"

    DEFAULT_PROMPT_TEMPLATE = (
        "The query is: {query}.\n\n\nThe student answered: {response}.\n\n\nThe correct answer is: {reference}.\n\n\n"
        "Reason whether the student answer is correct. If the student answer is correct, please say {correctness_template}. "
        "Otherwise, if the student answer is incorrect, say {incorrectness_template} and provide feedback to the student. "
        "The feedback should be specific and actionable."
    )

    DEFAULT_SYSTEM_PROMPT = "You're a helpful teacher who provides clear and constructive feedback."

    def __init__(self,
                 model: Optional[str] = None,
                 llm: Optional[AbstractModel] = None,
                 prompt_template: Optional[str] = None,
                 system_prompt: Optional[str] = None,
                 correctness_template: Optional[str] = None,
                 use_formatted_response: bool = False
                 ):
        """
        Initialize the VerbalGuide with an LLM and prompt templates.

        Args:
            model: The name of the LLM model to use (if llm is not provided)
            llm: An instance of AbstractModel to use for generating feedback
            prompt_template: Custom prompt template with {response} and {reference} placeholders
            system_prompt: Custom system prompt for the LLM
            correctness_template: Template to use when response is deemed correct by metric
            use_formatted_response: Whether to format the response with additional context; if False, the raw LLM response is returned
        """
        self.model = model
        self.llm = llm or LLM(model=model)
        self.prompt_template = prompt_template or self.DEFAULT_PROMPT_TEMPLATE
        self.system_prompt = system_prompt or self.DEFAULT_SYSTEM_PROMPT
        self.correctness_template = correctness_template or self.DEFAULT_CORRECTNESS_TEMPLATE
        self.use_formatted_response = use_formatted_response

    def get_feedback(self, query: str, response: str, reference: Optional[str] = None, **kwargs) -> Tuple[float, str]:
        """
        Get LLM-generated feedback by comparing response with reference information.

        Args:
            query: The query to analyze (e.g., user query, task, etc.)
            response: The response generated by LLM (e.g., student answer, code, etc.)
            reference: The expected information or correct answer
            **kwargs: Additional parameters (unused in this implementation)

        Returns:
            score: a float number provided by the metric function
            feedback: A string containing the LLM-generated feedback
        """
        if reference is None:
            raise ValueError("ReferenceGuide requires reference information to generate feedback")

        # Check if metric function indicates perfect match
        user_prompt = self.prompt_template.format(
                query=query,
                response=response,
                reference=reference,
                correctness_template=self.DEFAULT_CORRECTNESS_TEMPLATE,
                incorrectness_template=self.DEFAULT_INCORRECTNESS_TEMPLATE)

        messages = [
            {"role": "system", "content": self.system_prompt},
            {"role": "user", "content": user_prompt}
        ]

        llm_response = self.llm(messages=messages)

        # Extract the content from the response based on the LLM's response format
        if hasattr(llm_response, 'choices') and hasattr(llm_response.choices[0], 'message'):
            # For OpenAI-like response format
            llm_response = llm_response.choices[0].message.content
            # else: response is already the content

        # Format the output
        deliminator = "\n-------------------------------------\n"
        formatted_response = (
                f"The query is: {query}. The student answered: {response}. The correct answer is: {reference}. " + deliminator +
                "Expert feedback for generating the net content (if exists, please pay most attention to it):\n" +
                llm_response
        )

        score = 1 if 'Correct [TERMINATE]' in llm_response else 0

        return score, formatted_response if self.use_formatted_response else llm_response

    def forward(self, task: str, response: str, info: Any, **kwargs) -> Tuple[float, str]:
        score, feedback = self.get_feedback(task, response, info, **kwargs)
        return score, feedback
